# Generated by Django 4.0.4 on 2022-04-20 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casilleros3',
            fields=[
                ('casillero', models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='casillero')),
                ('vigencia', models.CharField(blank=True, default=True, max_length=100, verbose_name='vigencia')),
                ('vigencia_desde', models.DateField(blank=True, default=True, max_length=99, verbose_name='vigencia_desde')),
                ('vigencia_hasta', models.DateField(blank=True, default=True, max_length=100, verbose_name='vigencia_hasta')),
                ('co_titulares', models.CharField(blank=True, max_length=200, verbose_name='co_titulares')),
                ('autorizados_a_retirar', models.CharField(blank=True, max_length=200, verbose_name='autorizados_a_retirar')),
            ],
            options={
                'verbose_name': 'Casillero',
                'verbose_name_plural': 'Casilleros',
                'ordering': ['casillero'],
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=200, verbose_name='nombre_cliente')),
                ('telefono_cliente', models.CharField(max_length=100, verbose_name='telefono_cliente')),
                ('mail_cliente', models.EmailField(max_length=200, verbose_name='mail_cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre_cliente'],
            },
        ),
        migrations.CreateModel(
            name='Tramites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tramite', models.CharField(max_length=200, verbose_name='nombre_tramite')),
                ('descripcion_tramite', models.TextField(blank=True, verbose_name='descripcion_tramite')),
            ],
            options={
                'verbose_name': 'Tramite',
                'verbose_name_plural': 'Tramites',
                'ordering': ['nombre_tramite'],
            },
        ),
        migrations.CreateModel(
            name='Clientes_Tramites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha Creacion')),
                ('autos', models.CharField(max_length=200, null=True, verbose_name='autos')),
                ('estado_tramite_iniciado', models.BooleanField(default=True, verbose_name='Iniciado')),
                ('estado_tramite_finalizado', models.BooleanField(default=False, verbose_name='Finalizado')),
                ('estado_tramite_anulado', models.BooleanField(default=False, verbose_name='Anulado')),
                ('comentarios_tramite', models.TextField(blank=True, verbose_name='comentarios_tramite')),
                ('cliente_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tramites.clientes')),
                ('tramite_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tramites.tramites')),
            ],
            options={
                'verbose_name': 'Clientes_Tramites',
                'verbose_name_plural': 'Clientes_Tramite',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cedulas1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha Creacion')),
                ('autos', models.CharField(max_length=200, null=True, verbose_name='autos')),
                ('comentarios_cedula', models.TextField(blank=True, verbose_name='comentarios_cedula')),
                ('casillero_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tramites.casilleros3')),
            ],
            options={
                'verbose_name': 'Cedula',
                'verbose_name_plural': 'Cedulas',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='casilleros3',
            name='cliente_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tramites.clientes'),
        ),
    ]
